server {
    listen 80 default_server;
    server_name 54.90.30.187;
    location = /favicon.ico { access_log off; log_not_found off; }
    location /staticfiles/ {
        ubuntu /home/ubuntu/Django_WebApp;
    }
    location / {
        include proxy_params;
        proxy_pass http://unix:run/gunicorn.sock;
   }
}
